---
- name: Define the list of dev packages
  set_fact:
    packages:
      - code
      - gcc
      - git 
      - make

- name: Install dev packages
  dnf:
    name: "{{ packages }}"
    state: present

- name: Define the list of misc packages
  set_fact:
    packages:
      - alacritty
      - android-tools
      - bat
      - brave-browser
      - cbonsai
      - dconf
      - discord
      - fastfetch
      - gnome-tweaks
      - gnome-extensions
      - htop
      - libreoffice
      - ntfs-3g
      - papirus-icon-theme
      - steam
      - transmission
      - telegram-desktop
      - vim-enhanced
      - vlc
      - xournalpp

- name: Install misc packages
  dnf:
    name: "{{ packages }}"
    state: present

- name: Install Flatpak applications
  community.general.flatpak:
    name:
      - net.cozic.joplin_desktop
      - org.signal.Signal
      - com.spotify.Client
      - com.stremio.Stremio
    state: present