- name: Define the list of packages to remove
  set_fact:
    packages:
      - abrt-gui
      - abrt-desktop
      - fedora-bookmarks
      - fedora-chromium-config
      - gnome-abrt
      - gnome-boxes
      - gnome-calculator
      - gnome-calendar
      - gnome-clocks
      - gnome-contacts
      - gnome-maps
      - gnome-remote-desktop
      - gnome-tour
      - gnome-weather
      - rhythmbox
      - totem
      - yelp

- name: Remove specified packages
  dnf:
    name: "{{ packages }}"
    state: absent
  failed_when: false
