---
- name: Ensure dnf-plugins-core is installed
  dnf:
    name: dnf-plugins-core
    state: present

- name: Enable RPM Fusion Free and Non-Free Repositories
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_version'] }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: yes

- name: Ensure Flatpak is installed
  dnf:
    name: flatpak
    state: present

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

- name: Import Microsoft key
  command: rpm --import https://packages.microsoft.com/keys/microsoft.asc

- name: Add VSCode repository
  copy:
    dest: /etc/yum.repos.d/vscode.repo
    content: |  
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      autorefresh=1
      type=rpm-md
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc"

- name: Add Brave Browser repository
  copy:
    dest: /etc/yum.repos.d/brave-browser.repo
    content: |
      [brave-browser]
      name=Brave Browser
      enabled=1
      gpgcheck=1
      gpgkey=https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      baseurl=https://brave-browser-rpm-release.s3.brave.com/$basearch

