---
- name: Install Zsh Syntax Highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_user_home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  become: false

- name: Install Zsh Autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_user_home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become: false

- name: Deploy custom .zshrc
  ansible.builtin.template:
    src: .zshrc.j2
    dest: "{{ ansible_user_home }}/.zshrc"
    mode: '0644'
  become: false

- name: Change default shell to Zsh
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true
