---
- name: Ensure pip is installed
  dnf:
    name: python3-pip
    state: present

- name: Create directory for virtual environments
  file:
    path: "{{ ansible_user_home }}/prog/python_venvs/"
    state: directory
    mode: '0755'
  become: false

- name: Create Python virtual environments
  command: python -m venv {{ ansible_user_home }}/prog/python_venvs/{{ item }}
  loop:
    - crypto
  become: false

- name: Install packages in virtual environments
  pip:
    name:
      - pycryptodome
    virtualenv: "{{ ansible_user_home }}/prog/python_venvs/{{ item }}"
  loop:
    - crypto
  become: false

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item }}"
  loop:
    - docker.io/sagemath/sagemath
  become: false

- name: Get the latest version of Dive
  uri:
    url: "https://api.github.com/repos/wagoodman/dive/releases/latest"
    return_content: yes
  register: dive_release

- name: Extract the version number
  set_fact:
    dive_version: "{{ dive_release.json.tag_name | regex_replace('^v', '') }}"

- name: Install CTF packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - ghex
    - "https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.rpm"