---
- name: Ensure systemd user service directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_home }}/.config/systemd/user"
    state: directory
    mode: '0755'
  become: false

- name: Ensure theme switcher script directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_home }}/.local/bin/"
    state: directory
    mode: '0755'
  become: false

- name: Deploy Alacritty theme switcher script
  ansible.builtin.template:
    src: alacritty-theme-switch.sh.j2
    dest: "{{ ansible_user_home }}/.local/bin/alacritty-theme-switch.sh"
    mode: '0755'
  become: false

- name: Deploy systemd user service for Alacritty theme switching
  ansible.builtin.template:
    src: alacritty-theme.service.j2
    dest: "{{ ansible_user_home }}/.config/systemd/user/alacritty-theme.service"
    mode: '0644'
  become: false

- name: Reload systemd user daemon
  ansible.builtin.command: systemctl --user daemon-reload
  become: false

- name: Enable and start the theme-switching service
  ansible.builtin.systemd:
    name: alacritty-theme.service
    scope: user
    enabled: yes
    state: started
  become: false
